FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# babe-frequency-cap-ms

**Frequency Cap Microservice** helps another service such as **Push Notification Service** to limit push for __specific__ user by storing some temporary variable.

This service **IS NOT** limited to only __Push Notification Service__ use, each of the caller to this service is called an **App** and can be identified by `appId` on each request.

Each **App** should have a **Frequency Cap Strategy** and
each of them consists of list of **Frequency Filter**.

Each **Frequency Filter** should be defined in a single `class` of `IFrequencyCapFilter` implementation.

The **Frequency Cap Strategy** on the other hand, will be defined in a `JSON` config file.

Example of `freq-strategy.json` file would be:

``` json
[
  {
    "app": "push_notification",
    "strategy": {
      "filters": [
        {
          "class": "id.co.babe.frequencycap.filter.HourlyLimitFilter",
          "config": {
            "limit": 1
          }
        },
        {
          "class": "id.co.babe.frequencycap.filter.DailyLimitFilter",
          "config": {
            "limit": 4
          }
        },
        {
          "class": "id.co.babe.frequencycap.filter.MorningLimitFilter",
          "config": {
            "limit": 1
          }
        },
        {
          "class": "id.co.babe.frequencycap.filter.SleepingLimitFilter",
          "config": {
            "limit": 1
          }
        },
        {
          "class": "id.co.babe.frequencycap.filter.SameContentFilter",
          "config": {
            "limit": 1
          }
        }
      ]
    }
  }
]

```

`freq-strategy.json` JSON Schema

``` json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "app": {
        "type": "string"
      },
      "strategy": {
        "type": "object",
        "properties": {
          "filters": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "class": {
                  "type": "string"
                },
                "config": {
                  "type": "object",
                  "properties": {
                    "limit": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "limit"
                  ]
                }
              },
              "required": [
                "class",
                "config"
              ]
            }
          }
        },
        "required": [
          "filters"
        ]
      }
    },
    "required": [
      "app",
      "strategy"
    ]
  }
}
```

